[PC-1230] Update ESLOV information in Nicla Voice datasheet
arduino/docs-content pull request #1046
Opened 2023-05-12 06:59 UTC by canchebagur

## What This PR Changes
- This PR updates the ESLOV connector information in the Nicla Voice datasheet.

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-05-12 07:23 UTC, jcarolinares requested changes
Perform the small changes and ready to merge.

2023-05-12 07:23 UTC, jcarolinares commented on content/hardware/06.nicla/boards/nicla-voice/datasheet/datasheet.md
> +The manufacturer part number of the ESLOV connector is SM05B-SRSS, and its matching receptacle manufacturer part number is SHR-05V-S-B.
```suggestion
```

Duplicated please remove

2023-05-12 07:23 UTC, jcarolinares commented on content/hardware/06.nicla/boards/nicla-voice/datasheet/datasheet.md
> +### Sample Sketches
```suggestion

### Sample Sketches
```

adding a break line just for cleaning

2023-05-12 07:23 UTC, jcarolinares commented on content/hardware/06.nicla/boards/nicla-voice/datasheet/datasheet.md
> +**Notice**: Pin 1 of the ESLOV connector of the Nicla Voice board is a **5V voltage input**, not a voltage output. This means that the Nicla Voice is intended to be used as a secondary or a periphera
```suggestion
**Note**: Pin 1 of the ESLOV connector of the Nicla Voice board is a **5V voltage input**, not a voltage output. This means that the Nicla Voice is intended to be used as a secondary or a peripheral board of a main board or controller with an ESLOV connector with a 5V output like, for example, the Portenta H7.
```

2023-05-12 14:24 UTC, canchebagur commented
@jcarolinares PDF file updated with the latest changes.

2023-05-13 00:06 UTC, canchebagur commented
@jcarolinares done!

2023-05-15 07:46 UTC, jcarolinares approved these changes
Approved and merging

2023-05-15 07:46 UTC, merged