Add tutorial for IoT Cloud with MicroPython
arduino/docs-content pull request #1061
Opened 2023-05-19 13:04 UTC by sebromero

## What This PR Changes
- This PR adds a new tutorial that explains how to use the MicroPython library to access Arduino IoT Cloud

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-05-29 07:53 UTC, karlsoderby requested changes
Only minor changes, rest looks great.

2023-05-29 07:53 UTC, karlsoderby commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +- `client.start()`Enters a loop that runs as long as the board is connected to the cloud and synchronises data as it runs.
```suggestion
- `wifi_connect()` - Connects to your local WiFi using the credentials specified in secrets.py.
- `client.register` - Registers a variable that will be synced with the cloud.
- `on_switch_changed` - Is the callback that gets executed when the `ledSwitch` variable is changed by toggling the switch on the cloud dashboard. This function in turn toggles the on-board LED and updates the cloud variable `led` that reflects the state of the on-board LED to be displayed in the cloud dashboard.
- `client.start()` - Enters a loop that runs as long as the board is connected to the cloud and synchronises data as it runs.
```

2023-05-31 12:18 UTC, jhansson-ard requested changes
I left a couple of quick spell- and trademark checks ⭐

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +- Connect your Arduino device to your Wi-Fi network.
```suggestion
- Connect your Arduino device to your Wi-Fi® network.
```

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +Before we start, make sure you have MicroPython installed on your board. If you haven't you can follow [this tutorial](https://docs.arduino.cc/micropython/basics/board-installation). Then configure a
```suggestion
Before we start, make sure you have MicroPython installed on your board. If you haven't you can follow [this tutorial](https://docs.arduino.cc/micropython/basics/board-installation). Then configure a Thing in the [Arduino IoT Cloud](https://create.arduino.cc/iot/) consisting of two boolean variables called `led` and `ledSwitch`. To set up a Thing and a corresponding dashboard, please follow these two tutorials:
```

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +The resulting thing and dashboard should look similar to the following:
```suggestion
The resulting Thing and dashboard should look similar to the following:
```

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +Also, your device needs to be registered. Follow the flow "Any Device" ("Manual") when clicking "Add" in the "Devices" tab.
Please use bold when you are highlighting button names (if that is what these in " " are)

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +You will obtain a pair of device id and device key after registration. Store these details, along with your Wi-Fi credentials, in a `secrets.py` file. Here is an example of how `secrets.py` should lo
```suggestion
You will obtain a pair of device id and device key after registration. Store these details, along with your Wi-Fi® credentials, in a `secrets.py` file. Here is an example of how `secrets.py` should look like:
```

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +- `wifi_connect()` - Connects to your local WiFi using the credentials specified in secrets.py.
```suggestion
- `wifi_connect()` - Connects to your local Wi-Fi® using the credentials specified in secrets.py.
```

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +- Check the Wi-Fi credentials in the `secrets.py` file.
```suggestion
- Check the Wi-Fi® credentials in the `secrets.py` file.
```

2023-05-31 12:18 UTC, jhansson-ard commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +- Make sure your IoT Cloud "thing" is correctly set up and your device is assigned to it.
```suggestion
- Make sure your IoT Cloud Thing is correctly set up and your device is assigned to it.
```

2023-05-31 12:19 UTC, sebromero commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +Also, your device needs to be registered. Follow the flow "Any Device" ("Manual") when clicking "Add" in the "Devices" tab.
```suggestion
Also, your device needs to be registered. Follow the flow "Any Device" ("Manual") when clicking **Add** in the "Devices" tab.
```

2023-05-31 12:45 UTC, karlsoderby approved these changes
LGTM!

2023-05-31 13:03 UTC, sebromero commented on content/arduino-cloud/01.getting-started/10.iot-cloud-micropython/content.md
> +Also, your device needs to be registered. Follow the flow "Any Device" ("Manual") when clicking "Add" in the "Devices" tab.
```suggestion
Also, your device needs to be registered. Follow the flow "Any Device" ("Manual") when clicking **Add** in the "Devices" tab.
```

2023-05-31 13:10 UTC, merged