[PC-1432] - Portenta C33 User Manual Update
arduino/docs-content pull request #1434
Opened 2023-10-24 12:17 UTC by canchebagur

## What This PR Changes
- This PR updates the User Manual of the Portenta C33 with informtion related to the I2C ports. 

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-10-25 07:09 UTC, martab1994 reviewed
As said, I don't know if we need the note too, up to you :) otherwise, everything looks great to me!

2023-10-26 07:57 UTC, jcarolinares requested changes
Just one change that I will commit myself

The rest is perfect

thank you @canchebagur

2023-10-26 07:57 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/content.md
> +This user manual will provide a comprehensive overview of the Portenta C33 board, covering its major hardware and software elements. This user manual will also teach you how to set up, configure, and
Please mantain the original phrase, we are repeating this user manual two times when is not needed

```suggestion
This user manual will provide a comprehensive overview of the Portenta C33 board, covering its major hardware and software elements. With this user manual, you will learn how to set up, configure and use all the main features of the board.
```

2023-10-26 08:02 UTC, jcarolinares requested changes

2023-10-26 08:02 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/content.md
> +***Status column indicates the current status of the pins. "Free" means the pins are not in use by another resource or peripheral of the board and are available for usage, while "Shared" means the pi
```suggestion
To locate these pins on the board, please refer to the [board pinout section](#pinout) of the user manual. The `SDA0` and `SCL0` pins are also available through the onboard ESLOV connector of the Portenta C33.

***Note on I2C resources: System integrators can use the Portenta C33's High-Density connectors to expand the signals of the board to a custom-designed daughter board or carrier. Below is the I2C pins mapping on the board's High-Density connectors and shared resources:***

| **HD Connector** | **Interface** | **Pins** | **Status** | **Shared Peripherals** |
|:----------------:|:-------------:|:--------:|:----------:|:----------------------:|
|        J1        |     `I2C1`    |   43-45  |    Free    |            -           |
|        J2        |     `I2C0`    |   44-46  |    Free    |            -           |
|        J2        |     `I2C2`    |   45-47  |    Free    |            -           |

The status column indicates the current status of the pins. "Free" means the pins are not in use by another resource or peripheral of the board and are available for usage, while "Shared" means the pins are used by one or several resources or peripherals of the board.
```

Changes are for:
* The paparagrapth below can be considered as normal text/normal explanation. We are just explaining how the table works.
This way we can create a warning block on top for the system integrators

2023-10-26 08:19 UTC, jcarolinares requested changes

2023-10-26 08:19 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-c33/tutorials/user-manual/content.md
> +***Note on I2C resources: System integrators can use the Portenta C33's High-Density connectors to expand the signals of the board to a custom-designed daughter board or carrier. Below is the I2C pin
```suggestion
***System integrators can use the Portenta C33's High-Density connectors to expand the signals of the board to a custom-designed daughter board or carrier. Below is the I2C pins mapping on the board's High-Density connectors and shared resources:***

```

2023-10-26 08:28 UTC, jcarolinares approved these changes
LGTM

2023-10-26 08:28 UTC, merged