Machine Control Pinout update
arduino/docs-content pull request #145
Opened 2022-04-06 11:04 UTC by FunzioneFabio

Small fix, page 2, removed compatibility with PT1000.

2022-04-06 12:43 UTC, sebromero requested changes
Thank you for creating this PR! If you rename the file to `AKX00032-full-pinout.pdf` it will show up on the docs page, otherwise it won't.

2022-04-06 14:22 UTC, FunzioneFabio commented
Sorry I forgot about that, can I change the file name or should upload it a second time?

2022-04-07 13:43 UTC, marqdevx commented
You can change the name and make a new commit :)

2022-04-12 07:33 UTC, marqdevx approved these changes

2022-04-26 13:29 UTC, merged