added mkr 485 shield guide
arduino/docs-content pull request #1763
Opened 2024-02-16 10:02 UTC by jhansson-ard

## What This PR Changes
Added missing content for hardware

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-02-16 13:53 UTC, karlsoderby requested changes
Couple of suggestions and a couple of broken links found!

2024-02-16 13:53 UTC, karlsoderby commented on content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
> +This board may be used with the [Arduino RS485](/en/Reference/ArduinoRS485) and the [Arduino Modbus](/en/ArduinoModbus/ArduinoModbus) libraries, available from the Library Manager.
Old links that doesn't work anymore

2024-02-16 13:53 UTC, karlsoderby commented on content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
> +This shield may be used with the libraries already available for 485 communication.
```suggestion
## Use Cases

With the MKR 485 Shield you can interface with devices supporting the 485 standard. In the tutorial in the link below, you can learn how to interface with an **energy meter** using the Modbus protocol, and send the data to the Arduino Cloud.

- [Modbus Energy Meter and Arduino Cloud](https://docs.arduino.cc/arduino-cloud/application-notes/modbus-energy-meter/)
```

2024-02-16 13:53 UTC, karlsoderby commented on content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
> +### Usage Notes
```suggestion
## Usage Notes

```

2024-02-16 13:53 UTC, karlsoderby commented on content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
> +| Switch No. | ON                   | OFf            |
```suggestion
| Switch No. | ON                   | OFF            |

```

2024-02-16 15:23 UTC, jhansson-ard commented on content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
> +This board may be used with the [Arduino RS485](/en/Reference/ArduinoRS485) and the [Arduino Modbus](/en/ArduinoModbus/ArduinoModbus) libraries, available from the Library Manager.
```suggestion
This board may be used with the [Arduino RS485](https://www.arduino.cc/reference/en/libraries/arduinors485/) and the [Arduino Modbus](https://www.arduino.cc/reference/en/libraries/arduinomodbus/) libraries, available from the Library Manager.

```

2024-02-16 15:23 UTC, jhansson-ard commented on content/hardware/01.mkr/02.shields/mkr-485-shield/tutorials/getting-started/content.md
> +This board may be used with the [Arduino RS485](/en/Reference/ArduinoRS485) and the [Arduino Modbus](/en/ArduinoModbus/ArduinoModbus) libraries, available from the Library Manager.
Are these correct @karlsoderby ?

2024-03-05 09:50 UTC, karlsoderby approved these changes
LGTM!

2024-03-05 10:11 UTC, merged