Replace links to ephemeral file URLs with relative paths
arduino/docs-content pull request #1887
Opened 2024-04-19 13:16 UTC by per1234

## What This PR Changes

In addition to the Markdown content source files, this repository hosts non-text files. These are linked to in the content.

The website publishing system hosts these non-text files in paths under the `static` subfolder of the website (e.g., https://docs.arduino.cc/static/96e7dacc4383cd4a4a928872eca9e3da/ABX00112-step.zip). The path of the published file includes the file's [MD5 hash](https://en.wikipedia.org/wiki/MD5) (e.g., `96e7dacc4383cd4a4a928872eca9e3da`). This means that the URL will change every time the file is modified. For this reason, hardcoding links to these URLs in the content should be avoided whenever possible.

The website generation system automatically replaces links to relative paths with the equivalent ephemeral URL under the `static` subfolder of the website. This means that a link to the relative path of the file is functionally equivalent to linking the hardcoded ephemeral URL.

Although a relative path link is still prone to breakage if the content or target file is moved to a different location in the repository, this will probably occur less frequently than modifications to the files, making the relative path approach superior to the alternative of hardcoding the ephemeral URL.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

## Additional Context

This proposal addresses the concern raised at https://github.com/arduino/docs-content/pull/1881#discussion_r1568782232. An alternative solution is described at https://github.com/arduino/docs-content/pull/1881#discussion_r1570926638.

2024-04-19 16:14 UTC, jcarolinares commented
> Hey @per1234! 
> 
> I've added a task to the backlog to include the STEP files into the "static resource URL" system. Until that point, it's fine for me to implement your changes - but this is up to @jcarolinares and his team since they are responsible over the content itself (since this PR is concerning Pro product line) 👍🏼 

Yes, please proceed, Jacob will take care of the merge

2024-05-03 09:49 UTC, jcarolinares commented
Taking a look at this @jhansson-ard and @per1234 

These changes are not going to work until we have the relative paths for step files implemented, so I suggest to keep this pull request as a draft until then. Now it will only break even more the links.

Thanks!

2024-05-03 09:49 UTC, jcarolinares requested changes
Taking a look at this @jhansson-ard and @per1234

These changes are not going to work until we have the relative paths for step files implemented, so I suggest to keep this pull request as a draft until then. Now it will only break even more the links.

Thanks!

2024-05-03 13:24 UTC, per1234 commented
> These changes are not going to work until we have the relative paths for step files implemented

@jcarolinares how did you determine that it doesn't work? I verified this pull request by serving the website locally with the changes proposed here and the website generation system automatically replaces the relative path with the static file path just as I described:

![image](https://github.com/arduino/docs-content/assets/8572152/e8819bbf-c704-4e69-b8f7-1b554b16fd27)

And those links work perfectly to download the files.

2024-05-03 15:34 UTC, jcarolinares commented
> > These changes are not going to work until we have the relative paths for step files implemented
> 
> @jcarolinares how did you determine that it doesn't work? I verified this pull request by serving the website locally with the changes proposed here and the website generation system automatically replaces the relative path with the static file path just as I described:
> 
> ![image](https://private-user-images.githubusercontent.com/8572152/327766405-e8819bbf-c704-4e69-b8f7-1b554b16fd27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTA3MTQsIm5iZiI6MTcxNDc1MDQxNCwicGF0aCI6Ii84NTcyMTUyLzMyNzc2NjQwNS1lODgxOWJiZi1jNzA0LTRlNjktYjhmNy0xYjU1NGIxNmZkMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTUzMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDU2YjhkYjIwMGU0ODM1NjRmMTE3ODk2NGU1YzkzYzUzNTVhZjRmNjY1Y2Q0Y2U1MzZjNWU5YTFhZTI5ZTU5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RyI1XdpMs7N9vmycG4rofeniXXoMOMJAI3p-aWPfZNY)
> 
> And those links work perfectly to download the files.

That is a good point but I don't trust in local preview, there are technical differences between the local rendering and the cloud one.

Let's wait for @jhansson-ard confirmation then about that we can proceed, I prefer to wait until Monday than work twice, thank you both!

2024-05-06 08:12 UTC, jhansson-ard commented
@per1234 @jcarolinares We can try this on the staging platform as well, please use the workflow in the #prj_docs_deploy channel if you want to try it 🙏🏼

2024-05-06 11:12 UTC, jcarolinares approved these changes
Confirmed by @jhansson-ard is working

Approved

Thanks!

2024-05-06 14:21 UTC, merged