Updating trademarks in datasheets
arduino/docs-content pull request #1897
Opened 2024-04-25 07:38 UTC by jhansson-ard

## What This PR Changes
- Updated trademarks for mkr products datasheet

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-04-25 07:45 UTC, jhansson-ard commented on content/hardware/01.mkr/03.carriers/mkr-iot-carrier/datasheet/datasheet.md
> +### Getting Started - Arduino Cloud  Editor
```suggestion
### Getting Started - Arduino Cloud Editor 

```

2024-04-26 08:59 UTC, jacobhylen commented on content/hardware/01.mkr/01.boards/mkr-wifi-1010/datasheet/datasheet.md
> +Please make sure you are not directly connecting 5V signals to this board, or it will be damaged.
```suggestion
Please make sure you are not directly connecting 5 V signals to this board, or it will be damaged.

```

2024-04-26 09:03 UTC, jacobhylen requested changes
hej @jhansson-ard 
One small comment, otherwise lgtm

2024-04-26 11:07 UTC, jhansson-ard commented
Implemented your change @jacobhylen ! Thank you 🙏🏼

2024-05-06 09:29 UTC, jacobhylen approved these changes

2024-05-06 09:31 UTC, merged