Updating trademarks for Nano products
arduino/docs-content pull request #1898
Opened 2024-04-25 09:09 UTC by jhansson-ard

## What This PR Changes
- Updating trademarks and formatting for Nano products

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-04-26 08:53 UTC, jacobhylen requested changes
Hej @jhansson-ard 
Leaving a few comments here too :)

2024-04-26 08:53 UTC, jacobhylen commented on content/hardware/03.nano/boards/nano-every/datasheet/datasheet.md
> +If you want to program your Nano ESP32 while offline you need to install the Arduino Desktop IDE [1] To connect the Arduino Nano 33 BLE to your computer, you’ll need a Micro-B USB cable. This also pr
```suggestion
If you want to program your Nano Every while offline you need to install the Arduino Desktop IDE [1] To connect the Arduino Nano Every to your computer, you’ll need a Micro-B USB cable. This also provides power to the board, as indicated by the LED.

```

2024-04-26 08:53 UTC, jacobhylen commented on content/hardware/03.nano/boards/nano-rp2040-connect/datasheet/datasheet.md
> +The MP34DT06J microphone is connected via a PDM interface to the Nano RP2040 Connect. The digital MEMS microphone is omnidirectional and operate via a capacitive sensing element with a high (64 dB) s
```suggestion
The MP34DT06J microphone is connected via a PDM interface to the RP2040. The digital MEMS microphone is omnidirectional and operate via a capacitive sensing element with a high (64 dB) signal to noise ratio. The sensing element, capable of detecting acoustic waves, is manufactured using a specialized silicon micromachining process dedicated to produce audio sensors.

```
In this case it's actually referring to the MCU, not the entire board, so just RP2040 is correct

2024-04-26 08:53 UTC, jacobhylen commented on content/hardware/03.nano/boards/nano-rp2040-connect/datasheet/datasheet.md
> +The RP2040 (U1) has access to an additional 16 MB of flash memory via a QSPI interface. The execute-in-place (XIP) feature of the Nano RP2040 Connect allows external flash memory to be addressed and
```suggestion
The RP2040 (U1) has access to an additional 16 MB of flash memory via a QSPI interface. The execute-in-place (XIP) feature of the RP2040 allows external flash memory to be addressed and accessed by the system as though it were internal memory,  without first copying the code to internal memory.

```

2024-04-26 08:53 UTC, jacobhylen commented on content/hardware/03.nano/boards/nano-rp2040-connect/datasheet/datasheet.md
> +The Nano RP2040 Connect can be powered by either the Micro USB port (J1) or alternatively via VIN on JP2. An onboard buck converter provides 3V3 to the RP2040 microcontroller and all other peripheral
```suggestion
The Nano RP2040 Connect can be powered by either the Micro USB port (J1) or alternatively via VIN on JP2. An onboard buck converter provides 3V3 to the RP2040 microcontroller and all other peripherals. Additionally, the RP2040 also has an internal 1V8 regulator.

```

2024-04-26 11:09 UTC, jhansson-ard commented on content/hardware/03.nano/boards/nano-rp2040-connect/datasheet/datasheet.md
> +The RP2040 (U1) has access to an additional 16 MB of flash memory via a QSPI interface. The execute-in-place (XIP) feature of the Nano RP2040 Connect allows external flash memory to be addressed and
Thanks! I was unsure of this one! ⭐

2024-04-26 11:10 UTC, jhansson-ard commented on content/hardware/03.nano/boards/nano-every/datasheet/datasheet.md
> +If you want to program your Nano Every while offline you need to install the Arduino Desktop IDE [1] To connect the Arduino Nano Every to your computer, you’ll need a Micro-B USB cable. This also pro
```suggestion
If you want to program your Nano Every while offline you need to install the Arduino Desktop IDE [1] To connect the Nano Every to your computer, you’ll need a Micro-B USB cable. This also provides power to the board, as indicated by the LED.

```

2024-04-26 11:11 UTC, jhansson-ard commented
Implemented your changes @jacobhylen, thanks for the review! ⭐

2024-05-06 09:29 UTC, jacobhylen approved these changes

2024-05-06 09:31 UTC, merged