Updated datasheet links
arduino/docs-content pull request #1937
Opened 2024-05-13 15:48 UTC by pedromsousalima

## What This PR Changes
- Removed old RA4M1 datasheet and replaced it with the most up-to-date version from Renesas website

- Fixed links (one is using a fixed path and the other one is using a relative path but trying instead to look at a different directory level for testing reasons)

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-05-14 06:28 UTC, jhansson-ard reviewed
@pedromsousalima neither of the links work the way we intend. The first one shows the same issue as before, and the second leads to the GitHub source page instead of showing it on docs -> https://docs.arduino.cc/resources/datasheets/esp32-s3-mini.pdf

2024-06-11 09:24 UTC, jacobhylen requested changes
Hello @pedromsousalima.
These changes are in themselves good, but there are some things that need addressing before we can merge it. 
Left comments. :)

2024-06-11 09:24 UTC, jacobhylen commented on static/resources/datasheets/ra4m1.pdf
Please make sure that the replaced file is named the same way as the old one or links break.

2024-06-11 09:24 UTC, jacobhylen commented on content/hardware/02.hero/boards/uno-r4-wifi/datasheet/datasheet.md
Please add to the Change Log of the datasheet (section 22) an entry with this change.

2024-06-20 08:57 UTC, pedromsousalima commented on static/resources/datasheets/ra4m1.pdf
Fixed

2024-06-20 08:57 UTC, pedromsousalima commented on content/hardware/02.hero/boards/uno-r4-wifi/datasheet/datasheet.md
Fixed

2025-05-14 06:27 UTC, EMMANUEL2811UNITEC approved these changes

2025-05-14 07:47 UTC, jcarolinares commented
This pull request does not make sense anymore, closing

2025-05-14 07:47 UTC, closed without merging