Eric arduino due datasheet
arduino/docs-content pull request #1976
Opened 2024-05-23 14:38 UTC by Eric286

## What This PR Changes
- Added the firt revision of the Due Datasheet

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-05-27 12:05 UTC, jhansson-ard commented
Justa  note @Eric286, we've solved the issue with the spellchecker, just update your branch with main and you should be good to continue flawlessly with your PR-work ⭐

2024-06-11 13:05 UTC, jcarolinares requested changes
Review done

Pending little tasks:
- Final Block Diagram
- Final Power Tree

2024-06-11 13:18 UTC, jcarolinares approved these changes

2024-06-11 15:32 UTC, jcarolinares commented
Validade content linter not valid, but I need to gain control of the content to solve it, therefore I will do a legal swuash and merge to a new branch so I can fix it

2024-06-11 15:32 UTC, merged

2024-06-11 16:20 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/downloads/A000056-cad-files.zip
DONE

2024-06-11 16:20 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +-->
DONE

2024-06-11 16:21 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +The Arduino Due is a groundbreaking microcontroller board featuring the Atmel SAM3X8E ARM Cortex-M3 CPU, making it the first Arduino board built around a 32-bit ARM core microcontroller. With its 54
DONE

2024-06-11 16:21 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +**Warning: Unlike most Arduino boards, the Arduino Due board runs at 3.3V. The maximum voltage that the I/O pins can tolerate is 3.3V. Applying voltages higher than 3.3V to any I/O pin could damage t
DONE

2024-06-11 16:22 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +- **3D Printing & CNC Machines:** the Arduino Due can function as a versatile controller for DIY projects. By interfacing stepper motor drivers and endstop switches with the Due's numerous I/O pins,
DONE

2024-06-11 16:25 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| USB-to-serial         | **ATmega16U2** Connected to the SAM3X hardware UART                                  |
done

2024-06-11 16:26 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Analog Inputs         | The Due's analog inputs pins measure from ground to a maximum value of 3.3V (x12)    |
done

2024-06-11 16:26 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Digital Inputs        | Digital Inputs (x54) not 5 V compatible                                              |
done

2024-06-11 16:27 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Communication         | UART (x4), I2C (x2), SPI (x1 SPI header), Native USB port, Programming USB port      |
DONE

2024-06-11 16:27 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Power                 | Input voltage (VIN): 7-12 V / DC Current per I/O Pin: 8 mA                           |
done

2024-06-11 16:28 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Antipolarity protection       | yes                                            |
done

2024-06-11 16:28 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +**Note:** V<sub>DD</sub> controls the logic level and is connected to the 3.3V power rail. V<sub>AREF</sub> is for the analog logic.
done

2024-06-11 16:28 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Permissible range      | 6     | -   | 16   | V    |
done

2024-06-11 16:31 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +The Arduino due pinout is shown in the following figure.
done

2024-06-11 16:31 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +![Arduino due pinout](assets/ad-pinout.png)
done

2024-06-11 16:32 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +<strong>Safety Note:</strong> Disconnect power before board modifications, to avoid short-circuiting.
DONE

2024-06-11 16:33 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +#### 24-Pin Header
done

2024-06-11 16:34 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  2   | IOREF      | IOREF     | Reference for digital logic V - connected to 3.3V |
done

2024-06-11 16:35 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  20  | A11        | Analog    | Analog input 11 /GPIO                             |
done

2024-06-11 16:35 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  23  | CANRX      | Digital   | CAN Bus Receive                                   |
done

2024-06-11 16:35 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  24  | CANTX      | Digital   | CAN Bus Transfer                                  |
done

2024-06-11 16:35 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +<caption>24-Pin Header pinout</caption>
done

2024-06-11 16:36 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +#### 26-Pin Header
done

2024-06-11 16:36 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +<caption>26-Pin Header pinout</caption>
done

2024-06-11 16:37 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +
done

2024-06-11 16:37 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +
done

2024-06-11 16:37 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +<caption>JTAG pinout</caption>
done

2024-06-11 16:39 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +- The Due can also be powered using an external voltage source connected to the VIN pin, which has a recommended voltage range of 7 to 12 V.
done

2024-06-11 16:39 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +- The Power Jack: alternatively, the Due can be powered using a DC power supply connected to the power jack, which accepts a voltage range of 7 to 12 V.
done

2024-06-11 16:40 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +**It is essential to note that the Arduino Due operates at 3.3 V, so any external power sources must be regulated to this voltage level. Additionally, the power supply should be able to provide suffi
done

2024-06-11 16:41 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| 4   | n/c      |    -    | Not Connected    |
done

2024-06-11 16:41 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +#### 24-Pin Header Connector
done

2024-06-11 16:41 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +These pins offer a range of functionalities, including analog and digital input/output, power supply connections, analog-to-digital and digital-to-analog conversion, and CAN bus communication.
done

2024-06-11 16:42 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  20  | A11        | Analog    | Analog input 11 /GPIO                             |
done

2024-06-11 16:43 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  2   | IOREF      | IOREF     | Reference for digital logic V - connected to 3.3V |
done

2024-06-11 16:43 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +|  24  | CANTX      | Digital   | CAN Bus Transfer                                  |
done

2024-06-11 16:43 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +<caption>24-Pin Header pinout</caption>
done

2024-06-11 16:44 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +#### 26-Pin Header Connector
done

2024-06-11 16:44 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +<caption>26-Pin Header pinout</caption>
done

2024-06-11 16:44 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| 2   | +5V      | Internal | Power Supply of 5V           |
DONE

2024-06-11 16:45 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +The Arduino Due is a microcontroller board measuring 101.52 mm x 53.3 mm, featuring two USB-B connectors.</p>
done

2024-06-11 16:46 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +Connectors of the Arduino Due are placed on the left side of the board; their placement is shown in the figure below; all the dimensions are in mm.
done

2024-06-11 16:47 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| Diisobutyl phthalate (DIBP)            | 1000                    |
done

2024-06-11 16:47 UTC, jcarolinares commented on content/hardware/10.mega/boards/due/datasheet/datasheet.md
> +| MIC/Telec (Japan) |    No      |
done