[MKC-1703] Fixes for the Micropython course
arduino/docs-content pull request #2035
Opened 2024-06-19 14:46 UTC by BenjaminDannegard

## What This PR Changes
- Fixed a broken script
- Fixed text that was wrong

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-06-20 07:58 UTC, jacobhylen requested changes
Looks good, but while reviewing I found that there more many issues in one of the tutorials, and while we're at it let's fix it properly.

2024-06-20 07:58 UTC, jacobhylen commented on content/micropython/02.micropython-course/course/07.internet-of-things/01.internet-of-things.md
There are still some problems in this file. 
- There are 2 "exercise 2"s
- I can't get the "make a request" section to work on my Nano ESP32
- In Exercise 1 there is a sentence on line 98 that doesn't make any sense. 
- The code block that starts on line 100 tries to use the variables "WIFI_NETWORK" and "WIFI_PASSWORD" but they are not defined here.

2024-06-20 07:58 UTC, jacobhylen commented on content/micropython/02.micropython-course/course/03.python-cc/python-cc.md
Looks good.

2024-07-01 14:12 UTC, BenjaminDannegard commented on content/micropython/02.micropython-course/course/07.internet-of-things/01.internet-of-things.md
Need to test and fix the "make a request" section, everything else is fixed

2024-07-02 11:22 UTC, jacobhylen approved these changes
I realised that the reason I couldn't get the make a request section to work was user error :-) 
All is good. LGTM.

2024-07-03 11:47 UTC, merged