[PC-1851][PC-1857] Memory Partitioning Tutorial Improvement & PMC Update
arduino/docs-content pull request #2072
Opened 2024-07-16 23:00 UTC by ArduinoBot

## What This PR Changes
Updates the Memory partitioning tutorial to add compatibility with the Portenta Machine Control. It also adds minor instruction improvement regarding the requirement of certificates.h file when partitioning memory.
- Adds tutorial symlink to PMC

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-07-19 09:22 UTC, jcarolinares requested changes

2024-07-19 09:23 UTC, jcarolinares requested changes

2024-07-19 09:23 UTC, jcarolinares commented on content/hardware/07.opta/opta-family/opta/tutorials/08.memory-partitioning/content.md
> +- [Portenta Machine Control](https://store.arduino.cc/products/arduino-portenta-machine-control) (x1)
```suggestion
- Opta™ ([Opta™ Lite](https://store.arduino.cc/products/opta-lite), [Opta™ RS485](https://store.arduino.cc/products/opta-rs485), or [Opta™ WiFi](https://store.arduino.cc/products/opta-wifi)) (x1) or [Portenta Machine Control](https://store.arduino.cc/products/arduino-portenta-machine-control) (x1)
```

2024-07-19 15:53 UTC, TaddyHC commented on content/hardware/07.opta/opta-family/opta/tutorials/08.memory-partitioning/content.md
@jcarolinares alright, no problem! Then, I’ll dive deeper into this to add corresponding additional content as you said. It will be worth it, as I was sticking to the original scope of the task with known extensions. Nonetheless, I’ll have it updated once it is ready!

2024-08-02 04:46 UTC, TaddyHC commented on content/hardware/07.opta/opta-family/opta/tutorials/08.memory-partitioning/content.md
Ready for review with changes in place!

2024-08-02 09:01 UTC, jcarolinares approved these changes
Changes approved

Please wait to  my go to merge, we are waiting Matteo to fix stuff

2024-08-02 16:33 UTC, merged