Add pdf sync and invalidate old cloudflare cache
arduino/docs-content pull request #2077
Opened 2024-07-22 10:22 UTC by Matteo-it

## What This PR Changes

Actually we can't replace a datasheet file and keep the same url, as the files are distributed on a CDN. Since we decided to use static file for datasheet, we need to implement an action to invalidate old cache without store it.

2024-07-22 10:23 UTC, Matteo-it commented
@Serjlee you have access to repo setting page to add token and secrets?

2024-07-23 11:13 UTC, Serjlee commented on .github/workflows/deploy-production.yml
> -      - name: Sync all non-cacheable assets
Typo? I'd restore the old name

2024-07-23 11:29 UTC, Serjlee commented on .github/workflows/deploy-production.yml
> +          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
```suggestion
          cf_auth: ${{ secrets.CLOUDFLARE_PURGE_API_TOKEN }}
```

2024-07-23 11:29 UTC, Serjlee commented on .github/workflows/deploy-staging.yml
> +          cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
```suggestion
          cf_auth: ${{ secrets.CLOUDFLARE_PURGE_API_TOKEN }}
```

2024-07-23 11:31 UTC, Serjlee requested changes
Let's make sure to add `.pdf` as an `--exclude` of all syncs other than the pdf one, so they don't get deleted and then-reuploaded each time

2024-07-23 13:07 UTC, Matteo-it commented on .github/workflows/deploy-production.yml
> -      - name: Sync all non-cacheable assets
Yes typo error, sorry

2024-07-23 13:12 UTC, Matteo-it commented
> Let's make sure to add `.pdf` as an `--exclude` of all syncs other than the pdf one, so they don't get deleted and then-reuploaded each time

Updated both staging and prod actions

2024-07-26 07:02 UTC, Matteo-it commented
Hello, @Serjlee, i've try to put this branch in dev https://github.com/arduino/docs-content/actions/runs/10106670041 but it fail. Can you help me to try to understand the problem?

2024-08-05 15:24 UTC, merged