[PC-1782] - Opta Family Electrical Terminals Cable Size (Documentation)
arduino/docs-content pull request #2080
Opened 2024-07-22 19:17 UTC by canchebagur

## What This PR Changes
- This PR adds information on the electrical terminals' cable size to Opta's documentation. 

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-07-23 08:19 UTC, Fr4ng approved these changes

2024-07-23 18:36 UTC, mcmchris approved these changes
LGTM

2024-07-24 07:15 UTC, jcarolinares requested changes
Hello @canchebagur cc @mcmchris remember datasheets always must update the datasheet versioning

Missing and update in the versioning of the datasheet

Also please double check the format after this addition is correct and we don't have empty pages or format problems, thanks! :)

2024-07-25 15:26 UTC, jcarolinares approved these changes
Approved

2024-07-25 16:02 UTC, merged