Initial commit: Conveyor and sorting AppNote
arduino/docs-content pull request #2142
Opened 2024-09-02 13:17 UTC by DavidsonMSD

- Set up the initial project structure.
  - Added main project files.
  - Added assets.
  - Added PLC IDE code (including both Ladder and Sketch).

## What This PR Changes
- This PR adds the initial version of the conveyor and sorting application note.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-09-02 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/docs-content?pullRequest=2142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/docs-content?pullRequest=2142) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/docs-content?pullRequest=2142) it.</sub>

2024-09-03 21:26 UTC, mcmchris requested changes
@DavidsonMSD great application note, I like the way you adapt to suggestions and templates. 
I left some comments and suggestions mainly focused on format, titles and minor stuff. Feel free to ask for more details about them. 
cc. @jcarolinares

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +   - `#include <ArduinoIoTCloud.h>`: This library provides the necessary functions to connect and interact with the Arduino Cloud.
Nested lists not supported

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +### **Second Section: Setup Function**
```suggestion
### Second Section: Setup Function
```

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +   - `Serial.begin(9600);`: Initializes the serial communication at a baud rate of 9600, allowing you to monitor the device's output through the Serial Monitor.
```suggestion
   - `Serial.begin(9600);`: Initializes the serial communication at a baud rate of 9600 bps, allowing you to monitor the device's output through the Serial Monitor.
```

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +**Third Section: Loop Function**
```suggestion
### Third Section: Loop Function
```

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +**Third Section: Loop Function**
For title consistency

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +**Fourth Section:  InitProperties and Callbacks**
```suggestion
### Fourth Section:  InitProperties and Callbacks
```

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +![Arduino Cloud Dashboard](assets/conveyor-dashboard.gif)
Let's give you access to an enterprise Arduino Cloud plan so you can add more widgets and customize the dashboard.

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +### Arduino Sketch Code
Would be nice to have a screenshot of the PLC IDE so reader can mentally locate in the software where the code will be written.

2024-09-03 21:26 UTC, mcmchris commented on content/hardware/07.opta/opta-family/opta/tutorials/18.conveyor-sorting-app-note/content.md
> +## Opta Ladder Code
Would be nice to have a screenshot of the PLC IDE so reader can mentally locate in the software where the Ladder diagram will be written.

2024-10-02 13:26 UTC, mcmchris approved these changes
This is ready to publish! Thanks @DavidsonMSD for doing a great job with this Application Note!

2024-10-02 14:03 UTC, jcarolinares commented
Merging

2024-10-02 14:03 UTC, merged