Karlsoderby/giga can adc fixes
arduino/docs-content pull request #2184
Opened 2024-09-23 08:49 UTC by karlsoderby

The GIGA documentation had incorrectly labelled CANTX/CANRX pins (D93/D94) as ADC pins. These pins are not connected to the ADC.

- Update CANTX / CANRX mentions in CS / Audio guide.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-09-25 11:59 UTC, Hannes7eicher requested changes
I think the auto formatter got a little too excited and broke a few note banners :))

Although it also includes many fixes I would suggest we only change the pins and if we want to clean up articles we make a seperate PR. 

What do you think?

2024-09-26 08:10 UTC, karlsoderby commented
@Hannes7eicher totally agree. Changes fixed!

2024-09-26 09:15 UTC, Hannes7eicher approved these changes
two super small fixes I missed during the last review, otherwisee looks good!

2024-09-26 09:15 UTC, Hannes7eicher commented on content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
> +| D93       | CANRX           | Analog In, CAN                          |
```suggestion
| D93       | CANRX           | Digital IO pin, CAN                     |
```

2024-09-26 09:15 UTC, Hannes7eicher commented on content/hardware/10.mega/boards/giga-r1-wifi/tutorials/cheat-sheet/cheat-sheet.md
> +| D94       | CANTX           | Analog In, CAN                          |
```suggestion
| D94       | CANTX           | Digital IO pin, CAN                     |
```

2024-10-03 08:41 UTC, merged