Benjamindannegard/appwizard tutorial
arduino/docs-content pull request #2187
Opened 2024-09-24 11:52 UTC by BenjaminDannegard

## What This PR Changes
- Added a tutorial for using AppWizard on the Giga Display Shield

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-10-16 14:00 UTC, leonardocavagnis submitted a review, later dismissed

2025-03-14 16:14 UTC, mcmchris requested changes
Hey @BenjaminDannegard I reviewed the tutorial and left some minor comments. 

I would recommend for future tutorials to set your computer background to a solid color, (hex: D6EEF0) and to take screenshots directly on it so to avoid cropping images and giving consistency to the style.

2025-03-14 16:14 UTC, mcmchris commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +And lastly to create the Arduino sketch. Create an **examples** folder inside the root of the newly created folder, inside this **examples** folder you can create another folder containing the **demo
```suggestion
Finally, to create the Arduino sketch, create an **examples** folder inside the root of the newly created folder, inside this **examples** folder you can create another folder containing the **demo.ino** file. Use the following code for the **demo.ino**:
```

2025-03-14 16:14 UTC, mcmchris commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +Now all that is left is to import this whole folder as a library into the Arduino IDE. First compress the folder into a .zip format. And then in the Arduino IDE go to **Sketch -> Include library -> A
```suggestion
Now all that is left is to import this whole folder as a library into the Arduino IDE. First, **compress** the folder into a **.zip** format, then in the Arduino IDE go to **Sketch -> Include library -> Add .ZIP Library**, select the created .zip file and add it.
```

2025-03-14 16:14 UTC, mcmchris commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +
Would be nice to show a real photo of the Giga Display showing the UI.

2025-03-14 16:14 UTC, mcmchris commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +## Introduction
Would be nice to have a thumbnail here with the Giga Display showing a UI.

2025-03-24 11:02 UTC, jcarolinares commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +
hello @mcmchris please use an already done image on the tutorial to use it as initial image or a quick small trick so we can move this to publish! :pray:

2025-03-24 11:02 UTC, jcarolinares commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +## Introduction
idem about: hello @mcmchris please use an already done image on the tutorial to use it as initial image or a quick small trick so we can move this to publish! :pray:

2025-03-25 16:00 UTC, mcmchris commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +
Done!

2025-03-25 16:01 UTC, mcmchris commented on content/hardware/10.mega/shields/giga-display-shield/tutorials/13.appwizard-guide/content.md
> +## Introduction
Done!

2025-03-25 16:01 UTC, mcmchris approved these changes
LGTM! Now

2025-03-25 16:08 UTC, jcarolinares approved these changes
LGTM with the latest changes

2025-03-25 16:10 UTC, merged