[MKC-1832] MicroPython update examples with GIGA exception
arduino/docs-content pull request #2190
Opened 2024-09-24 15:16 UTC by pedromsousalima

## What This PR Changes
- Added exception for MicroPython when using GIGA boards

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-09-26 07:57 UTC, karlsoderby requested changes
Some minor changes @pedromsousalima , otherwise looking good!

2024-09-26 07:57 UTC, karlsoderby commented on content/micropython/01.basics/05.digital-analog-pins/digital-analog-pins.md
> +- `'A13'` is the pin markedas **DAC1**
```suggestion
- `'A13'` is marked as **DAC1** on the GIGA R1 WiFi

```

2024-09-26 07:57 UTC, karlsoderby commented on content/micropython/01.basics/05.digital-analog-pins/digital-analog-pins.md
> +On STM32 boards like the Arduino GIGA R1, PWM is handled differently. You need to use the `Timer` class along with the `Pin` class from the `pyb` module.
```suggestion
On STM32 boards like the [Arduino GIGA R1 WiFi](https://store.arduino.cc/products/giga-r1-wifi), PWM is handled differently. You need to use the `Timer` class along with the `Pin` class from the `pyb` module.

```

2024-09-26 10:51 UTC, pedromsousalima commented
@karlsoderby applied changes thanks!

2024-09-30 08:26 UTC, karlsoderby approved these changes

2024-09-30 09:47 UTC, merged