[PXCT-79] Nano Matter Official Launch
arduino/docs-content pull request #2290
Opened 2024-11-15 14:13 UTC by mcmchris

## What This PR Changes
- Product page update (community preview notes removed)
- Simple and full pinout update
- Block diagram and power tree update
- Datasheet update

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-12-02 13:16 UTC, jcarolinares requested changes
@mcmchris **Datasheet review done** , please ping me when that part is ready

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano-Matter_Top.png
good

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_Block_Diagram-v2.png
Clock signal and antenna, added, good

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_Connectors.png
Image updated to latest version, good

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_Outline.png
idem, good

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_PeripheralsActuators.png
good

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_Pinout.png
feedback provided by message, improve margins to have the board more centered + add a little warning explaining information about the bottom solder pads can be found on the full pinout

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_Power_Tree_1.png
pending lates version **with date updated**

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/datasheet.md
>  author: José Bagur
```suggestion
author: José Bagur, Christopher Méndez
```

2024-12-02 13:16 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/datasheet/datasheet.md
> +|    Input voltage from VIN pad    | V<sub>IN</sub>  |    6    |   7.0   |   21    |    V     |
great thank you

2024-12-02 14:28 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/features.md
checked

2024-12-02 14:29 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/image.svg
Image updated, checked

2024-12-02 14:31 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/interactive/ABX00112-pinout.png
waiting latest pinout @mcmchris

2024-12-02 14:31 UTC, mcmchris commented on content/hardware/03.nano/boards/nano-matter/datasheet/assets/Nano_Matter_Power_Tree_1.png
Done

2024-12-02 14:31 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/product.md
good, checked

2024-12-02 14:31 UTC, mcmchris commented on content/hardware/03.nano/boards/nano-matter/datasheet/datasheet.md
>  author: José Bagur
Done

2024-12-02 14:32 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/tech-specs.yml
all correct, checked

2024-12-02 14:32 UTC, mcmchris commented
@jcarolinares can go forward with this, everything ready.

2024-12-02 14:38 UTC, jcarolinares commented
> @jcarolinares can go forward with this, everything ready.

Datasheet changes addressed, **Datasheet is ready for launch, updating jira task**

2024-12-02 15:01 UTC, jcarolinares commented on content/hardware/03.nano/boards/nano-matter/interactive/ABX00112-pinout.png
now yes :)

2024-12-02 15:02 UTC, jcarolinares commented
This pull request is **ready**, thefore datasheet, product page/technical documentation is ready

2024-12-02 15:03 UTC, jcarolinares approved these changes
approved to be merge in other branches for launch

2024-12-03 10:28 UTC, jcarolinares commented
@mcmchris this is ready, I'm going to merge it in the official launch branch and pull request, also renamed to avoid confussion

2024-12-03 10:28 UTC, merged