add RTC RPC example
arduino/docs-content pull request #2298
Opened 2024-11-25 10:14 UTC by Hannes7eicher

## What This PR Changes
This PR adds an example on how to access the RTC from the M4 core on the Arduino GIGA R1 WiFi.

## Contribution Guidelines
- [x] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-12-03 10:21 UTC, karlsoderby requested changes
Hey @Hannes7eicher , appears to be working. However we are using the single sketch approach (uploading the same sketch to the different cores). 

I think it might be best to look at creating a specific M4 sketch, and a specific M7 sketch.

2024-12-03 13:18 UTC, Hannes7eicher commented
@karlsoderby I think that's a good idea! I split apart the sketch. Take a look and let me know what you think.

2024-12-03 14:55 UTC, karlsoderby commented on content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-dual-core/giga-dual-core.md
> +This example demonstrates how the RTC can be accessed from the M4:
```suggestion
The Real-time Clock (RTC) can be accessed from the M4 core, and using RPC, we can read the values.

In this example, we set the RTC to a specific date (can be adjusted in the example), send it to the M7 via RPC, and finally prints it out in the Serial Monitor using the M7 core. 
```

2024-12-03 14:56 UTC, karlsoderby commented on content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-dual-core/giga-dual-core.md
> +    //RTCset()  //Uncomment if you need to set the RTC for the first time.
```suggestion
    RTCset(); //sets the RTC to start from a specific time & date
```

2024-12-03 14:57 UTC, karlsoderby commented on content/hardware/10.mega/boards/giga-r1-wifi/tutorials/giga-dual-core/giga-dual-core.md
> +**M7 sketch:**
```suggestion
The M7 sketch is found below, and uses RPC to print out the incoming data from the M4.

**M7 sketch:**
```

2024-12-03 14:58 UTC, karlsoderby requested changes
Left some minor suggestion @Hannes7eicher . I think it's best to leave `RTC.set()` uncommented but let me know if there was a reason to leave like it that and we can adjust.

Otherwise everything looks great.

2024-12-04 09:33 UTC, Hannes7eicher commented
All suggestions applied 😁

2024-12-04 15:11 UTC, karlsoderby approved these changes

2024-12-05 10:22 UTC, merged