[PXCT-233] Opta: OPC UA Firmware Content
arduino/docs-content pull request #2324
Opened 2024-12-12 22:15 UTC by ArduinoBot

## What This PR Changes

Updates Opta User Manual with OPC UA firmware content

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2024-12-27 20:07 UTC, mcmchris approved these changes
This looks very good, I noticed the explanation is way better than the library Readme. LGTM

2025-01-02 11:59 UTC, jcarolinares requested changes
a picky/small change @TaddyHC , I'm gpoing to accept it myself so we can move on

2025-01-02 11:59 UTC, jcarolinares commented on content/hardware/07.opta/opta-family/opta/tutorials/01.user-manual/content.md
> +This section explains using the [**OPC UA library**](https://github.com/arduino-libraries/Arduino_OPC_UA) designed for Opta.
@TaddyHC Am I the only one who finds this sentence weird? Looks like it is "correct" but would like to make we do not have problems

```suggestion
This section explains the use of the [**OPC UA library**](https://github.com/arduino-libraries/Arduino_OPC_UA) designed for Opta.

```

2025-01-21 19:27 UTC, mcmchris commented
Merging to preview branch

2025-01-21 19:27 UTC, merged