[TC-362] Migrate MKR WiFi 1010 DS to MD
arduino/docs-content pull request #550
Opened 2022-09-20 09:21 UTC by aliphys

## What This PR Changes
- Migrate Google Docs version of MKR WiFi 1010 datasheet to MD

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2022-09-21 14:52 UTC, jcarolinares commented
@aliphys please try to run the Gatsby again, there was a technical problem that now should be already solved

2022-09-22 16:05 UTC, aliphys commented
@jcarolinares Thanks for the edits.
Are there any other changes you would like to see or can we merge this PR?

2022-09-23 10:25 UTC, jcarolinares commented
@aliphys yes, please solve this wrong link problem:

![image](https://user-images.githubusercontent.com/7687624/191941534-2c931f2b-96d7-418c-83e3-38870a09f296.png)

2022-09-23 10:43 UTC, jcarolinares requested changes

2022-09-23 11:05 UTC, aliphys commented on content/hardware/01.mkr/01.boards/mkr-wifi-1010/datasheet/datasheet.md
> +| Arduino Documentation     | https://docs.arduino.cc/hardware/nano                                                               |
```suggestion
| Arduino Documentation     | https://docs.arduino.cc/hardware/mkr-wifi-1010                                                               |
```

2022-09-23 13:39 UTC, merged