Portenta Machine Control: Hardware changes (Product Page + Datasheet)
arduino/docs-content pull request #559
Opened 2022-09-26 10:49 UTC by marqdevx

## What This PR Changes
- Reflect changes from the new hardware version.

2022-10-04 10:30 UTC, jcarolinares commented
[featured.png](https://github.com/arduino/docs-content/pull/559/files#diff-235d5f180a273f97ec7f542546b8602af3f25f77a363039e9f1c5460abcb6232) please change this image to the full product including the DIN bar supports

2022-10-05 15:30 UTC, jcarolinares requested changes
@marqdevx please take a look and accept the suggestions of the review if they are fine.

This is a WIP, due the web editor limitations we cannot comment the grey lines of the files, therefore one the suggestions are added, I will add commits to change the rest of the info

2022-10-07 12:21 UTC, marqdevx commented
@jcarolinares Updated the `featured` picture
Should we update the features list, to a table?

2022-10-13 09:43 UTC, jcarolinares reviewed
Changes done. WIP thought new commits by @jcarolinares

2022-10-26 07:23 UTC, marqdevx commented on content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/datasheet/datasheet.md
> +  - Three quadruple single pole single throw analog switches **TMUX1511RSVR** which are switching the active channel between the three available.
Align with the previous sentence
```suggestion
  - Three quadruple single-pole single-throw analog switches **TMUX1511RSVR** which are switching the active channel between the three available. 
```

2022-10-26 07:36 UTC, marqdevx commented on content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/datasheet/datasheet.md
> +The on-board real-time clock/calendar is the **PCF8563T/F4,118** which clock is provided by a dedicated external crystal oscillator:
```suggestion
The on-board real-time clock/calendar is the **PCF8563T/F4,118** its clock is provided by a dedicated external crystal oscillator:
```

2022-10-26 07:38 UTC, marqdevx commented on content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/datasheet/datasheet.md
> +  - A 100mF supercapacitor (**FC0V104ZFTBR24**) provides power to the **PCF8563T/F4,118** when the board power supply is disconnected. The RTC chipset will be powered by the supercapacitor for at lea
```suggestion
  - A 100mF super-capacitor (**FC0V104ZFTBR24**) provides power to the **PCF8563T/F4,118** when the board power supply is disconnected. The super-capacitor will supply the RTC chipset for at least 48 hours.
```

2022-10-26 07:48 UTC, marqdevx commented on content/hardware/05.pro-solutions/solutions-and-kits/portenta-machine-control/datasheet/datasheet.md
> +At each input of each channel, a PWM from the Portenta board is provided and filtered by a double low-pass filter, obtaining a DC output with a small AC ripple. The signal is then fed to the channel
```suggestion
At each input of each channel, a PWM from the board is provided and filtered by a double low-pass filter, obtaining a DC output with a small AC ripple. The signal is then fed to the channel non-inverting amplifier which amplifies it by 3.3.
```

2022-10-26 07:52 UTC, marqdevx commented
@jcarolinares 
I've just pushed some MD fixes, did some suggestions and I have some thoughts/issues:
* Isn't this duplicated? (4.5 Digital Programmable)
  ![image](https://user-images.githubusercontent.com/11246294/197959546-7d006fce-3ec1-401e-bc32-4e4bf68ffcc6.png)
* Why do we use A/D instead of ADC
* Analog Output (4.7) Should we use x3.3 instead 3.3 for the scale value? 
* Note information duplicated 
  ![image](https://user-images.githubusercontent.com/11246294/197960584-5bec4379-70a5-4250-9f69-ae0e4eff63b7.png)
* Please review the heading sentence `4.19 Half Speed Micro-USB Portenta Half-Speed USB Is Connected To The
Micro-USB Connector` 
* Analog Input section(4.6) bullet list, please check the Markdown style and the output style
  The markdown file looks like:
  ![image](https://user-images.githubusercontent.com/11246294/197965868-78d82fd4-ba5a-422f-bbc4-c3bfd56857fa.png)
  But the output is:
  ![image](https://user-images.githubusercontent.com/11246294/197966058-d8b2dcb1-c4fe-4fce-aafd-a4e1d138a5b1.png)

2022-12-09 15:19 UTC, sebromero commented
Any update on this?

2023-02-09 13:12 UTC, marqdevx commented
@jcarolinares What is the status of this?

2023-02-27 08:54 UTC, marqdevx commented
If possible, make clear the Latching compatible values

2023-04-06 10:17 UTC, jcarolinares commented
Branch is so outdated that not even the old render script is working

I'm going to move the work done to a new branch cloned from main

2023-04-14 10:30 UTC, marqdevx commented
@jcarolinares Check this branch
https://github.com/arduino/docs-content/compare/main...marqdevx/portenta-machine-control/datasheet-fixes

2023-07-19 08:03 UTC, closed without merging