Linter: USB-C Miss-spelling rule and content fix [PC1014, PC-1015]
arduino/docs-content pull request #620
Opened 2022-10-28 15:11 UTC by marqdevx

## What This PR Changes
- Linter: New rule to highlight the USB-C typos
  - Fix USB-C trademark miss-spells

2022-10-28 21:57 UTC, sebromero requested changes
See comments. You need to manually look through all changes when doing a search/replace action. The regex didn't work for me. Try with:

USB-C rocks!
USB-C® also!
http://www.usb-c.com
USB-Cable

2022-10-28 21:57 UTC, sebromero commented on content/hardware/03.nano/carriers/nano-motor-carrier/tutorials/nano-matlab-wifi-led/nanoMatlabWiFiLED.md
> +- [Micro USB Cable](https://store.arduino.cc/products/USB-C®able-type-a-male-to-micro-type-b-male)
Shouldn't match URLs

2022-10-28 21:57 UTC, sebromero commented on content/hardware/03.nano/carriers/nano-motor-carrier/tutorials/nano-simulink-wifi-led/nanoSimulinkWiFiLED.md
> +- [Micro USB Cable](https://store.arduino.cc/products/USB-C®able-type-a-male-to-micro-type-b-male)
Shouldn't match URLs

2022-10-28 21:57 UTC, sebromero commented on content/hardware/02.hero/boards/yun-rev2/tutorials/yun-first-config/content.md
> +  // copy from UART to USB-C®DC
Shouldn't match code blocks

2022-10-28 21:57 UTC, sebromero commented on content/hardware/02.hero/boards/yun-rev2/tutorials/yun-first-config/content.md
> +  int c = SERIAL_PORT_USBVIRTUAL.read();    // read from USB-C®DC
Shouldn't match code blocks

2022-10-28 21:57 UTC, sebromero commented on content/tutorials/projects/iot-air-quality-checker/iot-air-quality-checker.md
> +- [Arduino USB cable type A male to micro type B male](https://store.arduino.cc/USB-C®able-type-a-male-to-micro-type-b-male)
Same

2022-10-28 21:57 UTC, sebromero commented on scripts/validation/rules/rules-trademarks.yml
> +- regex: "(?:[uU][sS][bB]-[cC]|[uU][sS][bB] [tT]ype[ -cC][cC]|[uU][sS][bB][4](?!®)|usb-c)(?![-\\/]|\\.?\\S)"
```suggestion
- regex: "(?<!http[s]?:\\/\\/\\S*)(?:USB-C|USB Type[ -]C|USB4)(?!®)\\b"
  regexModifiers: "gi"
```

2022-10-31 08:54 UTC, marqdevx commented
Those errors where caused by the replace in vsc, my fault.
Fixed :)

2022-11-02 15:16 UTC, sebromero approved these changes
If you're confident there are no more false positives from the search & replaces operation we can merge it. I did not go through all the changes.

2022-11-02 17:10 UTC, marqdevx commented
I need to check/fix the "fix the issues" task, should I do it in another PR?

2022-11-02 23:04 UTC, merged