Update content.md with clearer instructions
arduino/docs-content pull request #84
Opened 2022-03-14 02:13 UTC by rkertesz

The instructions to install the library were very sparse. I learned much more from the README file in the pololu repo (https://github.com/pololu/vl53l1x-arduino). I pulled similar language into this document to help others who come after me.

## What Needs To Be Reviewed
Some readme language

2022-03-14 02:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino/docs-content?pullRequest=84) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino/docs-content?pullRequest=84) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino/docs-content?pullRequest=84) it.</sub>

2022-03-14 10:44 UTC, sebromero requested changes
Thank you for the contribution. I added a link to an article explaining the installation of libraries.

2022-03-14 10:44 UTC, sebromero commented on content/hardware/05.nicla/boards/nicla-vision/tutorials/proximity/content.md
> +Click "Install".
```suggestion
Click "Install". More detailed instructions on how to install a library can be found [here](/learn/starting-guide/software-libraries).
```
We have an article that explains how to install a library. I'd take the opportunity and reference it here.

2022-03-15 08:42 UTC, marqdevx commented
> @marqdevx Is this the correct library that is referenced?

Yes, it is also linked inside the meta data of the article.

2022-03-16 07:32 UTC, jhansson-ard reviewed
Added some suggestions to the formatting of the text. Let me know if they are acceptable!

2022-03-17 15:42 UTC, sebromero approved these changes
LGTM

2022-03-17 15:43 UTC, sebromero commented
@rkertesz Hi Ruben 👋 Thank you for your contribution. If you're happy with the suggestions that we've added we can merge this PR.

2022-03-18 13:28 UTC, rkertesz commented
@sebromero changes look good. Thank you

2022-03-18 13:28 UTC, rkertesz reviewed
changes improve clarity.

2022-03-18 14:00 UTC, merged