Portenta X8: Global Post Update
arduino/docs-content pull request #902
Opened 2023-03-10 01:03 UTC by TaddyHC

## What This PR Changes
It fixes, changes, and updates the following content:
- User Manual
- Multi-Protocol Gateway
- Waves Fleet Management

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-03-10 08:18 UTC, martab1994 approved these changes
Looks great to me =)

2023-03-10 11:01 UTC, jcarolinares requested changes
Review WIP

User manual changes requested related with permalinks

2023-03-10 11:08 UTC, sebromero commented on content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
> +* [Portenta X8 Datasheet](https://docs.arduino.cc/static/e12188dbbde2deba83f37965615c3c5a/ABX00049-datasheet.pdf)
> It is clear to me we are doing here something wrong
> 
> The hash is changing over time which means we should use a static link that will redirect to the last version of these resources.
> 
> @jhansson-ard or @sebromero do you know what is the right format to link to the datasheets?
> 
> Should be something similar to:
> 
> https://docs.arduino.cc/resources/datasheets/AFX00001-AFX00002-AFX00003-datasheet.pdf
> 
> Which means:
> 
> https://docs.arduino.cc/resources/datasheets/ABX00049-datasheet.pdf
@jcarolinares 
Correct. It copies those resources to the /resources folder which makes them available under the said URL. Here's where that happens: https://github.com/arduino/docs-content/blob/main/.github/workflows/deploy-prd.yml#L28-L34

2023-03-10 12:29 UTC, jhansson-ard commented on content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
> +* [Portenta X8 Datasheet](https://docs.arduino.cc/static/e12188dbbde2deba83f37965615c3c5a/ABX00049-datasheet.pdf)
@jcarolinares and yes, that is the correct way of adding the datasheet 🙏🏼

2023-03-10 12:32 UTC, jhansson-ard commented on content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
>  * [Portenta X8 Schematics](https://docs.arduino.cc/static/c92dbfc6c6a7c3f79c9987d36f017e48/ABX00049-schematics.pdf)
@jcarolinares please update the word `datasheets` to `schematics` in the link here ⭐

2023-03-10 13:04 UTC, jhansson-ard commented on content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
>  * [Portenta X8 STEP files](https://docs.arduino.cc/static/5d95e348688a9678e04d6f4d0b994844/ABX00049-step.zip)
I think we only have the special links for datasheets, schematics and pinouts ⭐

2023-03-10 15:03 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
>  * [Portenta X8 STEP files](https://docs.arduino.cc/static/5d95e348688a9678e04d6f4d0b994844/ABX00049-step.zip)
then keep this one as it is @TaddyHC !

2023-03-10 21:25 UTC, TaddyHC commented on content/hardware/04.pro/boards/portenta-x8/tutorials/01.user-manual/content.md
>  * [Portenta X8 STEP files](https://docs.arduino.cc/static/5d95e348688a9678e04d6f4d0b994844/ABX00049-step.zip)
Alright, will do that, thanks!

2023-03-14 13:12 UTC, jcarolinares approved these changes
Looks good to me

2023-03-14 13:12 UTC, merged