Chromebook guide update
arduino/docs-content pull request #92
Opened 2022-03-16 09:41 UTC by karlsoderby

Changed instructions to download IDE 1.8.x instead of IDE 2.0.x

2022-03-16 09:45 UTC, csarnataro commented
I think you haven't updated the command line itself, it is still 
`/Users/$(whoami)/Library/Arduino15/packages/arduino/tools/avrdude/6.3.0-arduino17/bin/avrdude`

2022-03-23 12:56 UTC, Lenardgeorge requested changes

2022-03-23 12:56 UTC, Lenardgeorge commented on content/hardware/02.hero/boards/uno-wifi-rev2/tutorials/uno-wifi-rev-2/uno-wifi-r2-chromebook-installation/uno-wifi-r2-chromebook-installation.md
Maybe its good to add the link to the HC article that talks about how to work on Chromebooks 
https://support.arduino.cc/hc/en-us/articles/360021251499-How-to-use-the-Web-Editor-with-Chromebook

2022-03-23 12:57 UTC, Lenardgeorge approved these changes

2022-03-23 13:25 UTC, merged