Portenta X8 Tutorials Banners
arduino/docs-content pull request #926
Opened 2023-03-17 01:13 UTC by canchebagur

## What This PR Changes
- This PR adds banners to all of the Portenta X8 tutorials.

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-03-17 05:03 UTC, TaddyHC reviewed
I have marked some items if some alternatives fit better for the tutorial's overview. Please have a look at it 🙂

2023-03-17 05:03 UTC, TaddyHC commented on content/hardware/04.pro/boards/portenta-x8/tutorials/11.display-output-webgl/hero-banner.png
For this, WebGL is the keyword, so maybe something like "WebGL Output" or "Displaying WebGL"?

2023-03-17 05:04 UTC, TaddyHC commented on content/hardware/04.pro/boards/portenta-x8/tutorials/04.python-arduino-data-exchange/hero-banner.png
Or simply "Data Exchange"?

2023-03-17 05:08 UTC, canchebagur commented on content/hardware/04.pro/boards/portenta-x8/tutorials/02.x8-fundamentals/hero-banner.png
@jcarolinares what do you think?

2023-03-17 05:08 UTC, canchebagur commented on content/hardware/04.pro/boards/portenta-x8/tutorials/04.python-arduino-data-exchange/hero-banner.png
@jcarolinares what do you think?

2023-03-17 05:08 UTC, canchebagur commented on content/hardware/04.pro/boards/portenta-x8/tutorials/06.waves-fleet-managment/hero-banner.png
@jcarolinares what do you think?

2023-03-17 05:08 UTC, canchebagur commented on content/hardware/04.pro/boards/portenta-x8/tutorials/11.display-output-webgl/hero-banner.png
@jcarolinares what do you think?

2023-03-17 11:13 UTC, jcarolinares requested changes
Looks great for me, changes requested regarding the naming of some banners, waiting for that to merge

2023-03-17 11:13 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-x8/tutorials/11.display-output-webgl/hero-banner.png
For this case I agree with @TaddyHC the topic of the tutorial is more related with WebGL Output or displaying WebGL than Video output

Please @canchebagur proceed with one of the @TaddyHC options

2023-03-22 09:45 UTC, jcarolinares approved these changes
Thanks for the changes to both

@canchebagur this is ready to merge, please proceed.

2023-03-22 13:47 UTC, merged