[PC-1178] Portenta H7 Family Tech Specs Update
arduino/docs-content pull request #954
Opened 2023-03-28 20:52 UTC by canchebagur

## What This PR Changes
- This PR changes the tech specs tables of the Portenta H7 family boards, standardizing them with the Portenta C33 board. 

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-03-29 11:00 UTC, jcarolinares requested changes
Please @GDJose help me to confirm some of this data with the sources. We want to be sure between all of us that we are not making mistakes.

Review only done at this moment for Portenta H7

2023-03-29 12:01 UTC, canchebagur commented on content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
> +  Analog pins: 8
Pins with analog functionality are 8, AREF is an analog pin. Analog **input** pins are 7.

2023-03-29 12:24 UTC, canchebagur commented on content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
> +  USB: USB 1.0/Full-Speed (x1) and USB 2.0/Hi-Speed (x1)
Double-checking the Altium files I found that only one SPI port is accessible to the user via the HD connectors and MKR-styled pins. Regarding the USB, the microcontroller datasheet states that one of the USB ports has double functionality, FS and HS, but in the schematics, it is shown explicitly as HS. What should we do in that case @jcarolinares? I initially put just the two ports that are shown in the schematic, FS and HS.

2023-03-29 15:21 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
> +  USB: USB 1.0/Full-Speed (x1) and USB 2.0/Hi-Speed (x1)
Let's keep it this way as we already talked during our 1x1

2023-03-29 15:22 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
> +  Analog pins: 8
As we already talk during oour one to one we will say Analog input pins and put 7

2023-03-29 15:50 UTC, canchebagur commented
@jcarolinares all of your comments and observations were addressed in the last commit, it should be ready now. Let me know your thoughts about it.

2023-03-31 09:07 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
> +  Channels: 8
@canchebagur please re-check this data, If I'm not wrong this should be 7 ???

2023-03-31 16:09 UTC, jcarolinares commented on content/hardware/04.pro/boards/portenta-h7/tech-specs.yml
> +  Channels: 8
Perfect

Solved.

2023-04-03 08:00 UTC, jcarolinares commented
thank you @TaddyHC for the nice trigger trick

2023-04-03 08:22 UTC, jcarolinares commented
Additional feedback from @martab1994 

Changes done and double-checked with Gatbsy Preview

Merging

2023-04-03 08:22 UTC, merged