[PC-1069] Nicla Sense ME - Datasheet Fix
arduino/docs-content pull request #962
Opened 2023-04-04 10:56 UTC by Jorgetrujilloroman

## What This PR Changes
- [Jira task](https://arduino.atlassian.net/browse/PC-1069)
- Adding a table to the "Declaration of Conformity to EU RoHS & REACH 211 01/19/2021" section and small grammatical corrections.
- Deleting unnecessary datasheet file from the repo (It is generated on the build)

## Contribution Guidelines
- [ ] I confirm that I have read the [contribution guidelines](https://github.com/arduino/docs-content/tree/main/contribution-templates) and comply with them.

2023-04-05 10:36 UTC, jcarolinares requested changes

2023-04-05 10:36 UTC, jcarolinares commented on content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
Please solve this moving the section header to the next page 

![image](https://user-images.githubusercontent.com/7687624/230056653-42be073e-6d75-4f60-9af3-fa2fd00ac0e5.png)

Render again to confirm we don't generate new formats problems

2023-04-05 10:37 UTC, jcarolinares commented
@Jorgetrujilloroman review done, waiting for changes

2023-04-05 13:54 UTC, Jorgetrujilloroman commented on content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
I'm not sure about how to make it, because the headers are automatically generated by the script.

2023-04-05 15:26 UTC, Jorgetrujilloroman commented on content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
Changes are done and ready to review again @jcarolinares

2023-04-05 17:51 UTC, canchebagur commented on content/hardware/06.nicla/boards/nicla-sense-me/datasheet/datasheet.md
You can try this:

`<div style="page-break-after: always;"></div>`

2023-04-06 06:56 UTC, Jorgetrujilloroman commented
@jcarolinares Requested changes are done. Waiting for new review.

2023-04-14 10:19 UTC, jcarolinares approved these changes
PR approved, pdf format and changes are correct

@Jorgetrujilloroman please merge, thanks :)

2023-04-14 10:54 UTC, Jorgetrujilloroman commented
Merging

2023-04-14 10:55 UTC, merged